# Generated by Django 4.1.5 on 2023-01-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_api', models.CharField(max_length=255)),
                ('openai_api', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matkul', models.CharField(max_length=225)),
                ('Dateline', models.DateTimeField()),
                ('Keterangan', models.TextField()),
                ('Status', models.IntegerField(choices=[(1, 'SELESAI'), (0, 'TIDAK SELESAI')], default=0)),
            ],
        ),
    ]
